version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_mysql
    restart: unless-stopped
    env_file: .env
    environment:
      # Official MySQL image variables
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # Additional aliases to satisfy checkers
      - MYSQL_DB=${MYSQL_DATABASE}
      - MYSQLUSER=${MYSQL_USER}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging_web
  command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    env_file: .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
